[auth]

user1_name = "Juda"
user1_hash = "RespiraOndo.J.A" 
user2_name = "Arydea"
user2_hash = "RespiraOndo.J.A"  

[spotify]
playlist_url = "https://open.spotify.com/playlist/3uLsAf1zak0giKxHNNMYFu?si=f478913aac6a464b"
